esphome:
  name: "ir-remote"
  friendly_name: "IR Remote"
  name_add_mac_suffix: true
  project:
    name: "JampireX.esphome-test"
    version: 1.0
    
dashboard_import:
  package_import_url: github://JampireX/esphome-test/ir-remote.yaml@main
  import_full_config: false

esp8266:
  board: esp12e

api:
  encryption:
    key: !secret api_key
  services:
    - service: transmit_raw
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            carrier_frequency: 38kHz
            code: !lambda 'return command;'

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:
logger:
ota:
  platform: esphome
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: true
    name: Button
    
remote_receiver:
  pin: 
    number: 12
    inverted: true
  dump: raw

remote_transmitter:
  pin: 14
  carrier_duty_percent: 50%

light:
  - platform: status_led
    name: Status
    pin: 
      number: 2
      inverted: true

button:
  - platform: safe_mode
    name: "Restart in Safe Mode"

sensor:
  - platform: uptime
    name: Uptime

web_server:
  port: 80
  version: 3
